require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'futligaapp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'futligaappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  # Comentar se for acima de XCode 12.4
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  
end

target 'futligaapp-tvOS' do
  # Pods for futligaapp-tvOS

  target 'futligaapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
